// The world's cast = the REAL registered Northline agents (src/lib/agents/ops/registry.ts). A test fails if this list drifts from the registry.
// Persona names are COSMETIC (so the world reads as people); the registry name/role is what the panel shows as the agent's identity.
// Nobody is invented for a role the registry does not have: missing roles appear only as NOT CONFIGURED (see NOT_CONFIGURED_ROLES).
export type PropKind = "tablet" | "tablet-grid" | "clipboard" | "checklist" | "headset" | "loupe" | "notebook" | "chart" | "sprout" | "none";
export type HatKind = "beret" | "cap" | "visor" | "beanie" | "bucket" | "none";
export interface RosterEntry {
  code: string; registryName: string; role: string; persona: string;
  color: string; accent: string; glyph: string; glyphName: string; prop: PropKind; hat: HatKind; skin: string; hair: string; bottom: string;
  /** Where simulated work happens (a workspace spot id in the town plan) and where the agent starts the session. */
  workspace: string; startSpot: string; idleSpots: string[]; workplaceLabel: string;
}
const COMMON_IDLE = ["promenade-bench-a", "boardwalk-rail-mid", "plaza-fountain", "hq-lounge-sofa", "cafe-table-a", "beach-edge"];
export const WORLD_ROSTER: RosterEntry[] = [
  { code: "ORCHESTRATOR", registryName: "Orchestrator", role: "Operator liaison and task router", persona: "Nova Reyes", color: "#3b82f6", accent: "#bfdbfe", glyph: "★", glyphName: "star", prop: "headset", hat: "none", skin: "#d9a67c", hair: "#1c1c24", bottom: "#2b3445", workspace: "hq-command-a", startSpot: "hq-command-a", idleSpots: ["hq-lobby-reception", "hq-meeting-table", "hq-lounge-sofa", "plaza-fountain"], workplaceLabel: "HQ · Command Center" },
  { code: "CONTENT_STRATEGIST", registryName: "Content Strategist", role: "Concepts and content mix", persona: "Theo Marchetti", color: "#14b8a6", accent: "#99f6e4", glyph: "◐", glyphName: "half-circle", prop: "notebook", hat: "none", skin: "#e0b48f", hair: "#3b2a1e", bottom: "#33423f", workspace: "strategy-house-desk", startSpot: "strategy-house-desk", idleSpots: ["strategy-house-terrace", "hq-meeting-table", "promenade-bench-a", ...COMMON_IDLE.slice(1)], workplaceLabel: "Strategy House" },
  { code: "CREATIVE_DIRECTOR", registryName: "Creative Director", role: "Scenes, styling, shot direction", persona: "Mara Quill", color: "#8b5cf6", accent: "#f0abfc", glyph: "◆", glyphName: "diamond", prop: "tablet", hat: "beret", skin: "#c98f68", hair: "#241a14", bottom: "#2c3340", workspace: "creative-studio-desk", startSpot: "creative-studio-terrace", idleSpots: ["creative-studio-terrace", "cafe-table-a", "boardwalk-rail-west", "hq-lobby-reception"], workplaceLabel: "Creative Studio" },
  { code: "PROMPT_ENGINEER", registryName: "Prompt Engineer", role: "Provider-ready prompts", persona: "Kai Okafor", color: "#06b6d4", accent: "#a5f3fc", glyph: "▲", glyphName: "triangle", prop: "tablet-grid", hat: "cap", skin: "#8d5a3b", hair: "#15110e", bottom: "#27333f", workspace: "prompt-studio-desk", startSpot: "prompt-studio-desk", idleSpots: ["prompt-studio-terrace", "cafe-table-b", "boardwalk-rail-west", ...COMMON_IDLE.slice(2)], workplaceLabel: "Prompt Studio" },
  { code: "CAPTION_WRITER", registryName: "Caption Writer", role: "Creator-voice copy", persona: "Isla Whitcombe", color: "#ec4899", accent: "#fbcfe8", glyph: "✎", glyphName: "pencil", prop: "notebook", hat: "beanie", skin: "#efc7a6", hair: "#a0522d", bottom: "#3a3040", workspace: "cafe-table-a", startSpot: "cafe-table-a", idleSpots: ["cafe-table-b", "boardwalk-rail-mid", "promenade-bench-a", "beach-edge"], workplaceLabel: "Copy Café" },
  { code: "IDENTITY_QA", registryName: "Identity QA", role: "Identity-critical checks", persona: "Dani Voss", color: "#f59e0b", accent: "#fde68a", glyph: "●", glyphName: "circle", prop: "loupe", hat: "none", skin: "#cf9a73", hair: "#2d2118", bottom: "#3b3226", workspace: "identity-lab-desk", startSpot: "identity-lab-desk", idleSpots: ["identity-lab-terrace", "hq-meeting-table", "plaza-fountain", "promenade-bench-b"], workplaceLabel: "Identity Lab" },
  { code: "CONTENT_QA", registryName: "Content QA", role: "Quality and duplication checks", persona: "Rafa Lindqvist", color: "#84cc16", accent: "#d9f99d", glyph: "✔", glyphName: "check", prop: "checklist", hat: "none", skin: "#e8c4a0", hair: "#6b4f2a", bottom: "#2e3a2a", workspace: "qa-studio-desk", startSpot: "hq-command-b", idleSpots: ["qa-studio-terrace", "hq-command-b", "promenade-bench-b", "cafe-table-b"], workplaceLabel: "QA Studio" },
  { code: "PRODUCTION_MANAGER", registryName: "Production Manager", role: "Productions, assets, approvals", persona: "Jules Harlan", color: "#10b981", accent: "#a7f3d0", glyph: "■", glyphName: "square", prop: "clipboard", hat: "visor", skin: "#b9805a", hair: "#1a1410", bottom: "#2a3a36", workspace: "production-office-desk", startSpot: "hq-production-desk", idleSpots: ["production-office-terrace", "hq-production-desk", "hq-lobby-reception", "plaza-fountain"], workplaceLabel: "Production Office" },
  { code: "PERFORMANCE_AGENT", registryName: "Performance Agent", role: "Analytics interpretation", persona: "Priya Nandakumar", color: "#f97316", accent: "#fed7aa", glyph: "▮", glyphName: "bar", prop: "chart", hat: "none", skin: "#a8744f", hair: "#16110f", bottom: "#3d2f28", workspace: "pier-desk", startSpot: "hq-analytics-desk", idleSpots: ["pier-rail", "hq-analytics-desk", "boardwalk-rail-west", "beach-edge"], workplaceLabel: "Analytics Pier" },
  { code: "GROWTH_STRATEGIST", registryName: "Growth Strategist", role: "Recommendations from data", persona: "Leo Castellan", color: "#ef4444", accent: "#fecaca", glyph: "✚", glyphName: "cross", prop: "sprout", hat: "bucket", skin: "#d4a073", hair: "#3a2a1a", bottom: "#352a2a", workspace: "growth-lab-desk", startSpot: "growth-lab-terrace", idleSpots: ["growth-lab-terrace", "pool-lounger-a", "boardwalk-rail-east", "promenade-bench-b"], workplaceLabel: "Growth Lab" },
];
export const ROSTER_BY_CODE = Object.fromEntries(WORLD_ROSTER.map((r) => [r.code, r])) as Record<string, RosterEntry>;

/** Roles the design wants but the registry does NOT have: shown as NOT CONFIGURED, never spawned as working agents. */
export const NOT_CONFIGURED_ROLES = [{ role: "Research Agent", location: "Research Observatory", note: "No Research Agent is registered; the observatory is an empty exterior reserved for it." }] as const;
export const roleStyle = (code: string) => ROSTER_BY_CODE[code] ?? { color: "#94a3b8", accent: "#e2e8f0", glyph: "✚", glyphName: "cross", prop: "none" as PropKind, hat: "none" as HatKind, registryName: code, persona: code, role: "", skin: "#d9a67c", hair: "#222", bottom: "#333", workspace: "", startSpot: "", idleSpots: [], workplaceLabel: "", code };
