// Emits SQL that upserts the canonical roster into Supabase (talent + canonical_identity). Roster in code is the source.
import { ROSTER } from "../src/lib/talent/roster";
import { buildCanonicalIdentity } from "../src/lib/identity/canonical";
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const rows = ROSTER.map((t) =>
  `(${q(t.code)}, ${q(t.name)}, ${q(t.first)}, ${t.age}, ${q(t.role)}, ${q(t.launchStatus)}, ${q(t.color)}, ${q(JSON.stringify(t.markets))}::jsonb, ${q(JSON.stringify(buildCanonicalIdentity(t.code)))}::jsonb)`);
console.log(`-- GENERATED by npm run db:seed-sql from src/lib/talent/roster.ts. Do not hand-edit.
insert into talent (code, name, first_name, age, role, launch_status, color, markets, canonical_identity) values
${rows.join(",\n")}
on conflict (code) do update set name=excluded.name, first_name=excluded.first_name, age=excluded.age, role=excluded.role,
  color=excluded.color, markets=excluded.markets, canonical_identity=excluded.canonical_identity;`);
